cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('success', views.cart_delete_all, name='cart_delete_all'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('take_order', views.take_order, name='take_order'),
    path('test_url/', views.test_view, name='test_view')
]

kolischa/urls.py
from django.contrib import admin
from shop import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as vws
from users.forms import CustomAuthForm
from django.contrib.auth import views as auth_views
from users.views import (ActivateView,
                         CheckEmailView,
                         SuccessView,
                         login,
                         registration,
                         reset_password)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile', include('users.urls', namespace='profile')),
    path('', include('shop.urls')),
    path('captcha/', include('captcha.urls')),
    path('api/', include('marks_api.urls')),
    path('logIn/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('exit', vws.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name="activate"),
    path('check-email/', CheckEmailView.as_view(), name="check_email"),
    path('success/', SuccessView.as_view(), name="success"),
    path('reset_password/', reset_password, name="reset_password"),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_done.html'), name='reset_password_done'),
    path('reset_password_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/reset_password_confirm.html"), name='reset_password_confirm'),
    path('reset_done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_password_complete.html'), name='password_reset_complete'),
    path('message', views.message)

]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('shop', views.ProductsView.as_view(), name='shop'),
    path('shop/product/<int:pk>', views.product_detail, name='product_detail'),
    path('shop/product/<int:pk>/update', views.UpdateProductView.as_view(), name='update_product'),
    path('shop/product/<int:pk>/delete', views.DeleteProductView.as_view(), name='delete_product'),
    path('repair/<str:type_name>/', views.repair, name='repair_page'),
    path('filter-data', views.filter_data, name='filter_data')
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from decimal import Decimal


class Category(models.Model):
    category = models.CharField(max_length=200)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Products(models.Model):
    title = models.CharField("Назва", max_length=200, unique=True)
    price = models.DecimalField("Ціна", max_digits=10, decimal_places=2, default=0)
    description = models.TextField("Опис товару", blank=True)
    count = models.IntegerField("Кількість товару в наявності", default=0)
    date = models.DateTimeField("Дата", default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField("Фото товару", upload_to='details_photo', default='static/shop/fon.jpg')

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class AvailableMarks(models.Model):
    name = models.CharField(max_length=200, blank=True)
    is_available = models.BooleanField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Available Mark'
        verbose_name_plural = 'Available Marks'
        ordering = ['name']


class PidMarks(models.Model):
    name = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Марка для підшипників'
        verbose_name_plural = 'Марки для підшипників'
        ordering = ['name']

shop/forms.py
from django import forms
from .models import Products
from django.views.generic import UpdateView

class SearchForm(forms.Form):
    search = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'myfield', 'placeholder': 'Пошук товара по назві'}), label='')


class RepairForm(forms.Form):
    FILTER_CHOICES = (
        ('some', '------------------'),
        ('bmw', 'bmw'),
        ('mersedes', 'mersedes'),
        ('audi', 'audi'),
    )

    name = forms.CharField(required=True, label='Ім`я')
    phone_number = forms.CharField(required=True, label='Номер телефону')
    marka_auto = forms.CharField(required=True, label='Номер телефону')
    model_auto = forms.CharField(required=True, label='Модель авто')
    type_of_repair = forms.CharField(required=True, label='Вид ремонту')

shop/views.py
import json
from django.conf import settings
from django.http import HttpResponse
from django.core import serializers
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render, redirect, reverse
from .models import Products, AvailableMarks, Category
from users.models import Order, TypeOfRepair, Cars
from kolischa import local_settings
from django.utils import timezone
from twilio.rest import Client
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib import messages
from cart.forms import CartAddProductForm
from .models import AvailableMarks, PidMarks
from users.models import TypeOfRepair
from .cars_dict import cars

from .forms import SearchForm, RepairForm


def home(request):
    start = 'Hello Kolischa'
    all_types_of_repair = TypeOfRepair.objects.all()
    data = {
        'AllTypesOfRepair': all_types_of_repair
    }

    return render(request, 'shop/home.html', data)


class ProductsView(ListView):
    model = Products
    template_name = 'shop/shop.html'
    context_object_name = 'products_list'
    paginate_by = 6
    ordering = ['-date']

    def get_context_data(self, **kwargs):
        form = SearchForm(self.request.POST or None)
        ctx = super(ProductsView, self).get_context_data(**kwargs)
        category_list = Category.objects.all()
        pid_list = PidMarks.objects.all()
        same_button = 'pid_butt'

        ctx['same_button'] = same_button
        ctx['pid_marks'] = pid_list
        ctx['category_list'] = category_list
        ctx['form'] = form
        return ctx

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)
        if form.is_valid() and form.cleaned_data.get('search') != '':
            search_word = form.cleaned_data.get('search').capitalize()
            tags = Products.objects.filter(title__contains=search_word)
            print(search_word)
            html = render_to_string('shop/ajax/shop.html', {'data': tags})
            return JsonResponse({'data': html})

        # if 'click' in request.POST:
        # # list with final product objects
        #     stuff = request.POST.get('cat')
        #     tags = Products.objects.filter(category__category=stuff)
        #     html = render_to_string('shop/shop.html', {'product_list': tags})
        #     return HttpResponse(html)


def filter_data(request):
    print(request.POST)
    if 'pid_butt' in request.POST:
        if 'category' in request.POST:
            category = request.POST.get('category')
            if category == 'Підшипники маточини (втулки)':
                marka = request.POST.get('pid_butt')
                b = Products.objects.filter(category__category='Підшипники маточини (втулки)')
                empty_list = []
                for item in b:
                    if marka in item.description:
                        empty_list.append(item)

                if len(empty_list) == 0:
                    return HttpResponse('Немає в наявності' + '*' + marka)
                html = render_to_string('shop/ajax/shop.html', {'data': empty_list})
                return JsonResponse({'data': html + '*' + marka + '*' + 'with_category'})
            elif category == 'Комплекти зчеплення':
                marka = request.POST.get('pid_butt')
                b = Products.objects.filter(category__category='Комплекти зчеплення')
                empty_list = []
                for item in b:
                    if marka in item.description:
                        empty_list.append(item)

                if len(empty_list) == 0:
                    return HttpResponse('Немає в наявності' + '*' + marka)
                flag = 'pid'
                html = render_to_string('shop/ajax/shop.html', {'data': empty_list, 'marka': marka})
                return JsonResponse({'data': html + '*' + marka + '*' + 'with_category'})
            elif category == 'Тормозні диски ПЕРЕДНІ':
                marka = request.POST.get('pid_butt')
                b = Products.objects.filter(category__category='Тормозні диски ПЕРЕДНІ')
                empty_list = []
                for item in b:
                    if marka in item.description:
                        empty_list.append(item)

                if len(empty_list) == 0:
                    return HttpResponse('Немає в наявності' + '*' + marka)
                html = render_to_string('shop/ajax/shop.html', {'data': empty_list})
                return JsonResponse({'data': html + '*' + marka + '*' + 'with_category'})
            elif category == 'Тормозні диски ЗАДНІ':
                marka = request.POST.get('pid_butt')
                b = Products.objects.filter(category__category='Тормозні диски ЗАДНІ')
                empty_list = []
                for item in b:
                    if marka in item.description:
                        empty_list.append(item)

                if len(empty_list) == 0:
                    return HttpResponse('Немає в наявності' + '*' + marka)
                html = render_to_string('shop/ajax/shop.html', {'data': empty_list})
                return JsonResponse({'data': html + '*' + marka + '*' + 'with_category'})
            elif category == 'Склоочисники':
                marka = request.POST.get('pid_butt')
                b = Products.objects.filter(category__category='Склоочисники')
                empty_list = []
                for item in b:
                    if marka in item.description:
                        empty_list.append(item)

                if len(empty_list) == 0:
                    return HttpResponse('Немає в наявності' + '*' + marka)
                flag = 'pid'
                html = render_to_string('shop/ajax/shop.html', {'data': empty_list, 'marka': marka})
                return JsonResponse({'data': html + '*' + marka + '*' + 'with_category'})
            elif category == 'Гальмові колодки':
                marka = request.POST.get('pid_butt')
                b = Products.objects.filter(category__category='Гальмові колодки')
                empty_list = []
                for item in b:
                    if marka in item.description:
                        empty_list.append(item)

                if len(empty_list) == 0:
                    return HttpResponse('Немає в наявності' + '*' + marka)
                flag = 'pid'
                html = render_to_string('shop/ajax/shop.html', {'data': empty_list, 'marka': marka})
                return JsonResponse({'data': html + '*' + marka + '*' + 'with_category'})
            elif category == 'Важелі підвіски':
                marka = request.POST.get('pid_butt')
                b = Products.objects.filter(category__category='Важелі підвіски')
                empty_list = []
                for item in b:
                    if marka in item.description:
                        empty_list.append(item)

                if len(empty_list) == 0:
                    return HttpResponse('Немає в наявності' + '*' + marka)
                flag = 'pid'
                html = render_to_string('shop/ajax/shop.html', {'data': empty_list, 'marka': marka})
                return JsonResponse({'data': html + '*' + marka + '*' + 'with_category'})
        else:
            marka = request.POST.get('pid_butt')
            b = Products.objects.all()
            empty_list = []
            for item in b:
                if marka in item.description:
                    empty_list.append(item)

            if len(empty_list) == 0:
                return HttpResponse('Немає в наявності')
            flag = 'pid'
            html = render_to_string('shop/ajax/shop.html', {'data': empty_list, 'flag': flag})
            return JsonResponse({'data': html + '*' + marka})
    else:
        stuff = request.POST.get('cat')
        tags = Products.objects.all().filter(category__category=stuff).order_by('-date')
        # код для сохранения данных из json в бд
        # for k, v in cars['list'].items():
        #     b2 = AvailableMarks(name=f'{k}', is_available=True)
        #     b2.save()
        #     print('good')

        html = render_to_string('shop/ajax/shop.html', {'data': tags})
        return JsonResponse({'data': html + '*' + stuff})


class UpdateProductView(UserPassesTestMixin, UpdateView):
    model = Products
    template_name = 'shop/update_product.html'

    fields = ['title', 'price', 'description', 'count', 'category', 'image']

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        messages.error(self.request, 'Сторінка не знайдена')
        return redirect('home')


class DeleteProductView(UserPassesTestMixin, DeleteView, SuccessMessageMixin):
    model = Products
    success_url = '/shop'  # после удаления будет переходить на главную страницу
    template_name = 'shop/delete_product.html'
    success_message = 'All good'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteProductView, self).delete(request, *args, **kwargs)

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect('home')


def product_detail(request, pk):
    all_objects_list = Products.objects.all()
    result_list = []

    for i in all_objects_list:
        if i.id == pk:
            result_list.append(i)

    cart_product_form = CartAddProductForm()

    data = {
        'result_list': result_list,
        'form': cart_product_form
    }

    return render(request, 'shop/product_detail.html', data)

shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"/>
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src=" https://unpkg.com/sweetalert/dist/sweetalert.min.js "></script>
    <link rel="stylesheet" href="/static/shop/main.css">
    {% block header %}
    <title>Головна</title>
    {% endblock %}
    <link rel="shortcut icon" href="#"/>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" style="margin-left: 10px;" href="{% url 'home' %}">Головна</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03"
            aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop' %}">Магазин</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'repair_page' type_name='Шиномонтаж' %}">Замовити послугу</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#footer">Контакти</a>
            </li>
            <div class="timals">
                <div class="cart_message">
                    {% with total_items=cart|length %}
                        <a href="{% url 'cart:cart_detail' %}"><img
                                src="{% static 'shop/premium-icon-add-to-cart-5412718.png' %}" class="w-100 icon_cart"
                                alt="..."
                                style=""></a>
                        <span class='badge badge-warning' id='lblCartCount'>{{ total_items }}</span>
                    {% endwith %}
                </div>

                {% if not user.is_authenticated %}
                    <a href="{% url 'registration' %}" style="text-decoration: none;">
                        <button class="btn btn-outline-info shapka_butt">Зареєструватися</button>
                    </a>
                    <a href="{% url 'login' %}" style="">
                        <button class="btn btn-outline-warning">Увійти</button>
                    </a>
                {% else %}
                    <a href="{% url 'profile:profile' %}" style="">
                        <button class="btn btn-outline-info profile_butt">Профіль</button>
                    </a>
                    <a href="{% url 'exit' %}" style="">
                        <button class="btn btn-outline-warning shapka_butt">Вийти</button>
                    </a>
                {% endif %}
            </div>
        </ul>
    </div>
</nav>
<main>

    {% block content %}
    {% endblock %}

</main>

<div class="proposal">
    <div class="proposal__close"></div>

    {% if not user.is_authenticated %}
        <div style="width: 100%; padding: 20px 10px;">
            <a href="{% url 'registration' %}" style="display: block; text-align: center;">Зареєструйтеся та майте
                можливість відслілковувати статус вашого ремонту та
                отримайте знижку на першу покупку запчастин 20%
            </a>
        </div>
    {% elif user.is_authenticated and sections == 'New_user' %}
        <div style="width: 100%; padding: 20px 10px;" class="discount">
            <a href="{% url 'shop' %}" style="display: block; text-align: center;">
                У вас діє знижка на перше замовлення товару 20%!
            </a>
        </div>
    {% endif %}
</div>

<script>
    const proposal = document.querySelector('.proposal');
    const closeBtn = proposal.querySelector('.proposal__close');

    if (!sessionStorage.activeProposal) {
        sessionStorage.activeProposal = "active";
    }

    if (sessionStorage.activeProposal === "disactive") {
        proposal.classList.add("proposal_disactive");
    }

    closeBtn.addEventListener('click', () => {
        proposal.classList.add("proposal_disactive");
        sessionStorage.activeProposal = "disactive";
    });
</script>


<footer id="footer" class="py-3 my-4 mt-5">
    <div class="content">
        <div class="footer__inner">
            <div class="footer__contacts">
                <ul>
                    <li>
                        <p>
                            Телефон
                        </p>

                        <a href="tel:+3805057734">+3805057734</a>
                    </li>

                    <li>
                        <p>
                            Email
                        </p>

                        <a href="mailto:golosov@gmail.com">golosov@gmail.com</a>
                    </li>

                    <li>
                        <p>
                            Адреса
                        </p>

                        <p>вулиця Чигиринська, 13А</p>
                    </li>
                </ul>
            </div>

            <div class="footer__map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2595.882303597431!2d32.107372895492524!3d49.411131402348104!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d14b2fc93b744f%3A0x5b86ae3d3556aa84!2z0KHQotCeIMKr0JrQvtC70ZbRidCwwrs!5e0!3m2!1sru!2sua!4v1649248906130!5m2!1sru!2sua"
                        allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>

    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'home' %}" class="nav-link px-2 text-muted">Головна</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 KOLISCHA</p>
</footer>
</body>

</html>

shop/templates/shop/delete_product.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<div class="container mt-5">
      <div class="row">
        <div class="col-md-8 submit_delete">
        <p><h2>Ви точно хочете видалити цей продукт "{{ object.title }}"?</h2></p>
        <form method="post" class="">
            {% csrf_token %}
            <button class="btn btn-outline-danger" type='submit'> Так, видалити</button>
            <a href="{% url 'product_detail'  object.id %}" class="btn btn-outline-success otmena">Ні, скасувати</a>
        </form>
        </div>

          <div class="col-md-4">

          </div>
      </div>
</div>

{% endblock %}

shop/templates/shop/product_detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                <div class="search-form">
                </div>

                <div class="alert alert-light">
                    {% for item in result_list %}
                        <img class="shopimg" src="/{{ item.image }}">
                        <div class="valik">
                            <div class="otstup" style="width: 100% !important;">
                            <div style="font-weight: 400; font-size: 35px; float: left;">{{ item.title }}</div>
                            <div style="float: right;">
                                {% if item.count == 0 %}
                                <h6 style="padding: 10px; color: red; font-size: 18px;">Немає в наявності</h6>
                                {% endif %}
                            </div>
                            </div>
                            <hr style="width: 550px">
                            <p class="otstup">{{ item.description|linebreaks }}</p>

                            <form method="post" class="otstup price" id="InToCart">
                                <h3>{{ item.price }} грн</h3>
                                <div class="valik2">
                                    <h6>Кількість: {{ form.quantity }}</h6>
                                    <input type="submit" class="btn btn-outline-success" name="submit"
                                           value="Додати до корзини"/>
                                </div>
                                {% csrf_token %}
                            </form>

                            {% if user.is_superuser %}
                                <p class="otstup">В наявності: {{ item.count }} шт</p>
                                <p><a href="{% url 'update_product' item.id %}" class="btn btn-outline-info">Редагувати
                                данні</a>
                            {% endif %}
                            {% if user.is_superuser %}
                                <a href="{% url 'delete_product' item.id %}"
                                   class="btn btn-outline-danger delete_button">Видалити продукт</a>
                            {% endif %}</p>


                        </div>
                        </div>



                        </div>

                        <div class="col-md-4">

                        </div>
                        </div>
                        </div>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                        <script>
                            $(document).ready(function () {
                                $("#InToCart").submit(function () {
                                    $.ajax({
                                        data: $(this).serialize(),
                                        type: $(this).attr('method'),
                                        url: "{% url 'cart:cart_add' item.id %}",
                                        success: function (response) {
                                            if (typeof (response) === 'string') {
                                                const myArray = response.split('$')
                                                console.log(myArray[0]);
                                                console.log(myArray[1]);
                                                if (myArray[1] === 'Нема товару') {
                                                    swal({
                                                        title: myArray[0],
                                                        icon: "error"
                                                    })
                                                }
                                            } else {
                                                $(".cart_message").load(" .cart_message");
                                                swal({
                                                    title: "Товар доданий до корзини!",
                                                    icon: "success",
                                                    buttons: {
                                                        cancel: 'До магазину',
                                                        confirm: "В корзину"
                                                    },
                                                }).then((value) => {
                                                    if (value === null) {
                                                        window.location.assign('{% url 'shop' %}');
                                                    } else {
                                                        window.location.assign('{% url 'cart:cart_detail' %}');
                                                    }
                                                });
                                            }
                                        }
                                    });
                                    return false;
                                });
                            })
                        </script>
                    {% endfor %}
{% endblock %}

shop/templates/shop/update_product.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<div class="container mt-5">
      <div class="row">
        <div class="col-md-8">
        <div class="search-form">
        </div>

        <div class="alert alert-light">
            <form method="post" class="" enctype="multipart/form-data">
                {% csrf_token %}
                    <p><label style="margin-right: 10px;">Назва: </label>{{ form.title }}</p>
                    <p><label style="margin-right: 10px;">Ціна: </label>{{ form.price }}</p>
                    <p><label style="margin-right: 10px;">Опис товара: </label>{{ form.description }}</p>
                    <p><label style="margin-right: 10px;">Кількість: </label>{{ form.count }}</p>
                    <p><label style="margin-right: 10px;">Категорія: </label>{{ form.category }}</p>
                    <p><label style="margin-right: 10px;">Фото</label>{{ form.image }}</p>
                <button class="btn btn-warning" type='submit'>Оновити</button>
            </form>
        </div>



        </div>

          <div class="col-md-4">

          </div>
      </div>
</div>

{% endblock %}